class Affranchissement:
    index: int
    nom_departement: str
    nom_produit: str
    total_montants: str
    total_objets: int
    total_poids: int
    poids_unite: int
    date: str
    poids_min: int
    poids_max: int